### ISSUE TITLE
Does not work on Arduino UNO

### ISSUE THREAD

**Issue by MovingSymbols** [usefulsensors/person_sensor_arduino#1]
The code as presented does not work on an original Arduino UNO (the grandaddy of them all, AVR-based). Sensor works (LED lights) but something's wrong with the I2C part because the code never actually detects anything.

I (crudely) was able to get raw I2C data with my own test code by just checking byte numbers 4 (# of faces) and 10 (confidence of face #0) so I can tell the sensor works, but I'm not smart enough to know what's wrong with this example code as written. But it definitely doesn't work on the UNO.

**Comment by jschrempp** [comment]
Does not work on the Particle.io Argon either

**Comment by jschrempp** [comment]
Crudely, just to get going, try modifying line 82 in person_sensor_h to

`if (Wire.available() != 32) {`

and line 86 to

`for (unsigned int i=0; i < 32; ++i) {`

**Comment by petewarden** [comment]
Thanks @MovingSymbols and @jschrempp! I'm guessing your diagnosis is correct, but I've also ordered an Uno to test with. I'm hoping it's the same underlying problem as https://github.com/usefulsensors/person_sensor_arduino/issues/2 and the fix for that will address this too, but I'll update this bug once I know.

**Comment by petewarden** [comment]
@MovingSymbols I've checked in a fix to read I2C in smaller chunks and tested it on an Uno. Could you take a look and let me know if this fixes it for you too if you get a chance? Thanks for your patience!

**Comment by MovingSymbols** [comment]
@petewarden Looks like that did it, I am getting results on an UNO now. Thanks!
